### ISSUE TITLE
Enabling root access not work with Windows Phone 8.0.10517.150

### ISSUE THREAD

**Issue by FakerEXE** [ReneLergner/WPinternals#66] opened 2024-02-03 19:24 UTC
### Description

I have a Nokia Lumia 620 RM-846 running Windows phone os version 8.0.10517.150 and while Windows Phone Internals can detect the device, read out its device info and unlock the devices boot loader I can't get Windows Phone Internals to enable root access on the device, I'm not sure if enabling root access on version 8.0.10517.150 is supported by Windows Phone Internals but is it isn't I would appreciate if you added that support to Windows Phone Internals.

### Expected behavior

Mouting the EFIESP.bin.pz and MainOS.bin.pz then unlocking the images with Windows Phone Internals should result in getting root access on the image.

### WPinternals Version

v2.9.2

### Windows Version

Windows 11 23H2 22631.3085

### Phone model

Lumia 620 RM-846

**Comment by gus33000** [comment] 2024-10-12 22:48
Duplicate of #70

**Closed by gus33000** 2024-10-12 22:48 UTC
Labels: bug
