### ISSUE TITLE
It does not show anything in the download section. please help me

### ISSUE THREAD

**Issue by MIRDEHGH** [ReneLergner/WPinternals#87] opened 2024-12-30 10:15 UTC
### Description

![image_2024-12-30_134132736](https://github.com/user-attachments/assets/d9325b07-792b-49ca-95b7-74838d669bba)

I am in Iran and I wanted to use the download section, but it doesn't show anything. I even used V2Ray, but nothing, and I even changed the product type, but it still doesn't show anything.

### Expected behavior

dosent showing anything

### WPinternals Version

All versions

### Windows Version

windows 10 Ghost Spectre

### Phone model

lumia 435

**Comment by gus33000** [comment] 2024-12-31 07:40
Duplicate of #86, see #86 for resolution

**Closed** 2024-12-31 07:40 UTC
Labels: bug
