### ISSUE TITLE
Slow Downloading issue

### ISSUE THREAD

**Issue by amin137398** [ReneLergner/WPinternals#14] opened 2021-01-16 08:35 UTC
hi
I'm currently experiencing super slow download issue while downloading FFU file for my lumia 625 . I tried using different internet connection but even with 50 Mbps connection I only get to download with 100 or 200 KBps ! which is too slow and if the download process somehow get interrupted even for one second , it will stop downloading and freezes . 
is they any other way to get this file ? any direct download link or something ? 
![download](https://user-images.githubusercontent.com/27921772/104807288-238c5180-57f3-11eb-8433-bc1979cdd51e.png)

**Comment by gus33000** [comment] 2021-08-11 16:31
Hi

We just released a new version with a fix for this issue: https://github.com/ReneLergner/WPinternals/releases/tag/2.9

Can you tell us if the issue is indeed resolved? It shouldn't freeze anymore.

Thanks!

**Closed** 2024-10-12 22:52 UTC
